// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { GameType } from "./GameType";
import type { Terrain } from "./Terrain";

export type Field = { terrain: Terrain, game_type: GameType, };
