// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type Field = { terrain: Terrain, game_type: GameType, };

export type GameType = "Single" | "Double";

export type Terrain = "None" | "Electric" | "Grassy" | "Psychic" | "Misty";

export type Weather = "None" | "Sand" | "Sun" | "Rain" | "Hail" | "Snow" | "HarshSunshine" | "HeavyRain" | "StrongWings";
