// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type Move = { name: string, };

export type MoveCategory = "Physical" | "Special" | "Status";

export type MoveFlags = { contact: boolean, bite: boolean, sound: boolean, kick: boolean, horn: boolean, bone: boolean, punch: boolean, bullet: boolean, pulse: boolean, slicing: boolean, wind: boolean, field: boolean, air: boolean, weather: boolean, };

export type MoveTarget = "AdjacentAlly" | "AdjacentAllyOrSelf" | "AdjacentFoe" | "All" | "AllAdjacent" | "AllAdjacentFoes" | "Allies" | "AllySide" | "AllyTeam" | "Any" | "FoeSide" | "Normal" | "RandomNormal" | "Scripted" | "SSelf";
