// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type MoveFlags = { contact: boolean, bite: boolean, sound: boolean, kick: boolean, horn: boolean, bone: boolean, punch: boolean, bullet: boolean, pulse: boolean, slicing: boolean, wind: boolean, field: boolean, air: boolean, weather: boolean, };
