// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type Nature = "Adamant" | "Bashful" | "Bold" | "Brave" | "Calm" | "Careful" | "Docile" | "Gentle" | "Hardy" | "Hasty" | "Impish" | "Jolly" | "Lax" | "Lonely" | "Mild" | "Modest" | "Naive" | "Naughty" | "Quiet" | "Quirky" | "Rash" | "Relaxed" | "Sassy" | "Serious" | "Timid";
