// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Species } from "./Species";

export type Nature = "Adamant" | "Bashful" | "Bold" | "Brave" | "Calm" | "Careful" | "Docile" | "Gentle" | "Hardy" | "Hasty" | "Impish" | "Jolly" | "Lax" | "Lonely" | "Mild" | "Modest" | "Naive" | "Naughty" | "Quiet" | "Quirky" | "Rash" | "Relaxed" | "Sassy" | "Serious" | "Timid";

export type Pokemon = { specie: Species, hp: number, hp_max: number, };

export type PokemonStatus = "Sleep" | "Poison" | "Burn" | "Freeze" | "Paralyz" | "Toxic";

export type PokemonType = "Normal" | "Fighting" | "Flying" | "Poison" | "Ground" | "Rock" | "Bug" | "Ghost" | "Steel" | "Fire" | "Water" | "Grass" | "Electric" | "Psychic" | "Ice" | "Dragon" | "Dark" | "Fairy" | "Unknown";
